find_trending_tokens:
  description: >
    Identify 3-5 tokens in the {sector} that are currently trending based on recent news coverage, significant announcements, or high discussion volume discovered via web search ({current_date}).
    Focus on the *reasons* (news, events, narratives) why they are trending.
    Use the SerperDevTool to search for recent news and discussions related to tokens in the {sector}.
    Explicitly cite the source URLs for the information backing the trending reason.
    Do NOT invent metrics, percentages, specific commit numbers, or dates. Summarize the actual findings from search results.
  expected_output: >
    A structured list (JSON format) of trending tokens. Each entry must include:
      - name: The token's name.
      - ticker: The token's ticker symbol (use 'N/A' if not easily found).
      - trending_reason: A concise summary (1-2 sentences) of the specific news, event, or narrative causing the token to trend, based *only* on search results.
      - source_urls: A list of actual URLs from the search results that support the trending_reason.
  agent: trending_token_finder
  output_file: output/trending_tokens.json
  # Removed search_query_template as it might be too specific and lead to less diverse results initially. Let the agent formulate queries based on the goal.

research_trending_tokens:
  description: >
    Perform in-depth web research on each trending token from the context ({current_date}). For each token:
    1. Summarize key recent news, updates, and narratives surrounding the token using web search results.
    2. Assess and summarize the general social media/community sentiment (positive, negative, neutral) based on search findings.
    3. Locate and provide direct URLs to the token's official website, documentation, and primary code repository (e.g., GitHub).
    4. Search for and provide direct URLs to relevant on-chain analytics dashboards (e.g., Dune, Etherscan, DefiLlama, specific block explorers) where metrics like wallet distribution, transaction activity, and TVL (if applicable) can be found.
    5. Briefly summarize the token's core technology and primary use case.
    Prioritize information from reliable sources found via web search.
  expected_output: >
    A structured research report (JSON format) containing a list of objects, one for each token. Each object should include:
      - Token Name
      - Summary of Recent News & Narratives
      - Summary of Social Sentiment
      - URL to Official Website
      - URL to Documentation (if found)
      - URL to Code Repository (if found)
      - URLs to relevant On-Chain Data Dashboards (list of links found)
      - Summary of Technology & Use Case
      - List of primary source URLs used for the summary.
  agent: token_researcher
  context:
    - find_trending_tokens
  output_file: output/research_report.json

pick_best_token:
  description: >
    Analyze the research report provided in the context, which includes summaries of news, sentiment, technology, use cases, and links to official resources and data dashboards for several trending tokens in the {sector}.
    Based *only* on the provided research summary (news, sentiment, tech/use case) and the *potential insights* suggested by the linked resources (official site, docs, repo, dashboards), select the single most promising token for potential investment.
    Your evaluation should consider factors like: recent positive news/developments, strong positive sentiment, clear utility/use case, apparent development activity (suggested by repo link presence), and potential for insights from linked data dashboards.
    Do NOT invent metrics or scores. Base your decision on a qualitative assessment of the summarized information and the availability/implication of linked resources.
    After choosing, send a push notification summarizing the pick and the main reason (1 sentence).
    Finally, provide a rationale explaining why the chosen token was selected and briefly why the others were not, based on the research context.
  expected_output: >
    A markdown report containing:
      - The name of the chosen token.
      - A detailed rationale for the selection, referencing specific points from the research context (news summary, sentiment, use case, availability of resource links).
      - A brief explanation for why other tokens from the research context were not selected.
      - Confirmation that the push notification was sent.
  agent: token_picker
  context:
    - research_trending_tokens
  output_file: output/decision.md
  # Removed scoring_weights as the input data format has changed and direct scoring is no longer feasible without hallucination or dedicated tools.